### ISSUE TITLE
[FEATURE] Add `requires_oe_package` and `call_openeye` utilities

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-utilities#14]
## Description

It may be useful to add a new decorator similar to `requares_package` explicitly for OpenEye libraries, whereby the decorator handles both import and license checks e.g. [here](https://github.com/openforcefield/openff-recharge/blob/4509bc1d4a00fb8ca9abae5dd93425dd05fd65e4/openff/recharge/utilities/openeye.py#L25-L52) and [here](https://github.com/SimonBoothroyd/constructure/blob/db3a9e0afb2e98e451959fb62009a733a2cac546/constructure/utilities/openeye.py#L16-L43).

Additionally, it may be useful to add a `call_openeye` utility that wraps calls to `bool` returning OE functions and raises exceptions on `False` returns and redirects any output to an appropriate logger e.g. [here](https://github.com/openforcefield/openff-recharge/blob/4509bc1d4a00fb8ca9abae5dd93425dd05fd65e4/openff/recharge/utilities/openeye.py#L80-L129).

cc @mattwthompson

**Comment by mattwthompson** [comment]
Agreed; yesterday I used `from openff.toolkit.tests.utils import requires_openeye`, which should never really be imported as such.

**Comment by mattwthompson** [comment]
I'm not super familiar with using OpenEye calls, so I don't totally follow what's going on in `call_openeye`. How much would need to be changed to upstream it to here? Just changing the exception type?
