### ISSUE TITLE
Expose `MissingOptionalDependency` at the top level

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-utilities#20]
It would be useful to expose `MissingOptionalDependency` through the `openff.utilities` module rather than needing to import `openff.utilities.utilities` which should maybe be made private?

**Comment by mattwthompson** [comment]
Sure, that sounds reasonable. I assume you'd prefer everything be accessible in that way - `from openff.utilities import this_utility`? Any other things you find yourself importing frequently?

**Comment by mattwthompson** [comment]
Oh, looks like that's actually housed in `openff.utilities.exceptions`, but accessible through `openff.utilities.utilities` via it being imported in that module.

On one hand, I see the value of exposing everything from the highest module level. On the other hand, that might  grow unwieldy if in a year everything is exposed in one place, i.e. if this package grows to have several dozen exceptions, helper classes/functions/decorators, etc.
