### ISSUE TITLE
Check for `mamba` vs. calling `conda`

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-utilities#60]
```shell
conda list | grep "^conda" | wc -l
       0
```

Conda provides an "API" that can be hacked, but Mamba's API doesn't give an option to just list the installed packages.

* https://github.com/conda-forge/openff-bespokefit-feedstock/pull/18#issuecomment-1748817005
* https://github.com/openforcefield/openff-utilities/blob/v0.1.9/openff/utilities/provenance.py#L11
* https://github.com/openforcefield/openff-utilities/pull/12#discussion_r674919361

**Comment by mattwthompson** [comment]
Although `conda` is aliased, or something, so even though it's not installed as a Python package, the CLI calls work fine and its executable is found.

```python
In [1]: import subprocess

In [2]: subprocess.check_output(["conda", "list"]).decode().split("\n")[:10]
Out[2]:
['# packages in environment at /Users/mattthompson/mambaforge/envs/openff-toolkit-test:',
 '#',
 '# Name                    Version                   Build  Channel',
 'ambertools                23.3            py311ha883923_2    conda-forge',
 'amberutils                21.0                     pypi_0    pypi',
 'anyio                     4.0.0              pyhd8ed1ab_0    conda-forge',
 'appnope                   0.1.3              pyhd8ed1ab_0    conda-forge',
 'argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge',
 'argon2-cffi-bindings      21.2.0          py311heffc1b2_4    conda-forge',
 'arpack                    3.7.0                h58ebc17_2    conda-forge']

In [3]: from openff.utilities import has_executable

In [4]: has_executable("conda")
Out[4]: True

In [5]: import conda
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 import conda

ModuleNotFoundError: No module named 'conda'

**Comment by mikemhenry** [comment]
Sorry I wasn't more clear in my PR, having `mamba` or `conda` installed works fine, the issue is if a user (hi I'm the user, I'm the problem, it's me) is using `micromamba`, there is no `conda` alias. So if I `micromamba install openff-utilities` then call ` _get_conda_list_package_versions` I will get an error. This only happens if someone is using package manager like `micromamba` but I am guessing that users of `pixi` would have the same issue.

**Comment by mattwthompson** [comment]
Good to know! I assumed `micromamba` would alias it, but didn't think of trying.

Could you run this snippet for me in your setup?

```python
>>> from openff.utilities import has_executable
>>> for executable in ['conda', 'mamba', 'micromamba']:
...     print(executable, has_executable(executable))
```

I get
```
conda True
mamba True
micromamba False
```
and I suppose you'll get the opposite?

**Comment by mikemhenry** [comment]
Yes, ~I can make a PR to use micromamba if there is no `conda`~

```
>>> from openff.utilities import has_executable
>>> for executable in ['conda', 'mamba', 'micromamba']:
...  print(executable, has_executable(executable))
... 
conda False
mamba False
micromamba True
>>> 
```

Never mind looks like you are working on one
