### ISSUE TITLE
valid micromamba installation not found by openff utils

### ISSUE THREAD

**Issue by atravitz** [openforcefield/openff-utilities#89]
Currently, micromamba can be installed and run correctly even if its installation location is not in the user's `$PATH`: https://github.com/mamba-org/mamba/issues/2577

This leads to a discrepancy where the micromamba installation is completely valid, but then openff fails with a `openff.utilities.exceptions.CondaExecutableNotFoundError`.

I would expect that if `micromamba` (or `conda`, `mamba`, etc.) runs successfully, that openff should be able to detect it as well. Can https://github.com/openforcefield/openff-utilities/blob/main/openff/utilities/provenance.py be updated to be more robust to this, and less dependent on searching for specific installation locations?

**Comment by j-wags** [comment]
This is a really interesting proposal. I'm trying to think of the case where a user is in a properly initialized micromamba env, but doesn't have micromamba in their path, are there other environment variables we can look at to determine where the micromamba executable is?

**Comment by mikemhenry** [comment]
I am not sure yet how to do it, but I do think making [find_executable](https://github.com/openforcefield/openff-utilities/blob/98acba9ae171c9c78e7a5bf001559658fde88082/openff/utilities/utilities.py#L135-L153) aware of shell functions would resolve this issue.

**Comment by mikemhenry** [comment]
Also, should this trigger an exception? Perhaps a warning about being unable to check package versions would be better.

**Comment by mattwthompson** [comment]
This has become too much work compared to the benefit provided, I'm just going to have it warn and return an empty dictionary when something goes wrong.

**Comment by mikemhenry** [comment]
Thanks @mattwthompson!

**Comment by cyrushu** [comment]
If you do ```conda install conda``` within your environment, you can pass the find_executable function

**Comment by mikemhenry** [comment]
Yes, installing `conda` or `mamba` into an environment will fix this (for future people running into this error).

**Comment by mattwthompson** [comment]
Look for this in the next release, probably version 0.1.13 and sometime on the week of December 2nd

(I don't make releases on Fridays and next week is a holiday week in which many of us are half-off.)
